set shell := ["powershell.exe", "-Command"]

default:
    @just --list

uv:
    uv sync
    uv lock

mypy:
    mypy .

ruff:
    ruff check --fix
    ruff format

pre-commit: mypy ruff

unit-test:
    uv run pytest

test-cov:
    uv run pytest --cov=src --cov-fail-under=85 --cov-report=html