[project]
name = "duelbase"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mypy",
    "ruff",
    "pydantic",
    "pytest",
    "pytest-cov",
    "loguru"
]
[tool.coverage.run]
omit = [
    "src/main.py",
    "*/__init__.py",
    "src/user_interface/*"
]